import { ResumeTemplateConfig } from "./types";

export const ALL_RESUME_TEMPLATES: ResumeTemplateConfig[] = [
  {
    id: "modern",
    name: "Modern ATS",
    description: "Clean 2026 ATS-friendly layout with strong hierarchy",
    wrapperClass: "space-y-6 text-slate-900",
    headerClass: "flex items-center gap-4 border-b-2 border-emerald-600 pb-4",
    nameClass: "text-3xl font-bold text-emerald-700",
    titleClass: "text-slate-600",
    contactClass: "text-slate-700",
    headingClass: "text-emerald-700",
    skillClass: "bg-emerald-100 text-emerald-900",
    photoClass: "h-20 w-20 rounded-full border-2 border-emerald-600 object-cover",
  },
  {
    id: "executive",
    name: "Executive Board",
    description: "Premium leadership template with navy and gold accents",
    wrapperClass: "space-y-6 border-t-8 border-slate-950 p-6 text-slate-900",
    headerClass: "border-b-2 border-amber-500 pb-5",
    nameClass: "text-4xl font-serif font-bold text-slate-950",
    titleClass: "text-amber-700 font-medium",
    contactClass: "text-slate-700",
    headingClass: "text-amber-700 uppercase tracking-wide",
    skillClass: "bg-amber-100 text-amber-900",
    photoClass: "h-20 w-20 rounded-sm border-2 border-amber-500 object-cover",
  },
  {
    id: "consultant",
    name: "Consultant Pro",
    description: "McKinsey-style structured consulting resume",
    wrapperClass: "space-y-5 p-5 text-slate-900",
    headerClass: "border-b-4 border-indigo-700 pb-4",
    nameClass: "text-3xl font-bold tracking-tight text-indigo-900",
    titleClass: "text-slate-600",
    contactClass: "text-slate-700",
    headingClass: "text-indigo-800 uppercase tracking-wider",
    skillClass: "bg-indigo-50 text-indigo-900 ring-1 ring-indigo-200",
    photoClass: "h-20 w-20 rounded border-2 border-indigo-700 object-cover",
  },
  {
    id: "tech",
    name: "Tech Lead",
    description: "Developer-focused layout with technical feel",
    wrapperClass: "space-y-5 border-l-4 border-blue-600 p-5 font-mono text-slate-900",
    headerClass: "rounded-lg bg-slate-100 p-4",
    nameClass: "text-2xl font-bold text-blue-700",
    titleClass: "text-slate-600",
    contactClass: "text-slate-700",
    headingClass: "text-blue-700",
    skillClass: "bg-blue-100 text-blue-900",
    photoClass: "h-20 w-20 rounded-lg border-2 border-blue-600 object-cover",
  },
  {
    id: "product",
    name: "Product Manager",
    description: "Outcome-focused PM layout with clean metrics spacing",
    wrapperClass: "space-y-6 rounded-xl border border-sky-200 p-5 text-slate-900",
    headerClass: "flex items-center gap-4 rounded-xl bg-sky-700 p-5 text-white",
    nameClass: "text-3xl font-bold text-white",
    titleClass: "text-sky-100",
    contactClass: "text-sky-100",
    headingClass: "text-sky-700",
    skillClass: "bg-sky-100 text-sky-900",
    photoClass: "h-20 w-20 rounded-full border-2 border-white object-cover",
  },
  {
    id: "minimal",
    name: "Minimal One Page",
    description: "Lightweight recruiter-friendly single-page format",
    wrapperClass: "space-y-4 p-2 font-light text-slate-900",
    headerClass: "border-b border-slate-300 pb-4 text-center",
    nameClass: "text-3xl font-light tracking-wide text-slate-900",
    titleClass: "text-slate-500",
    contactClass: "justify-center text-slate-600",
    headingClass: "text-slate-800",
    skillClass: "bg-slate-100 text-slate-800",
    photoClass: "mx-auto mb-3 h-20 w-20 rounded-full object-cover grayscale",
    layout: "compact",
  },
  {
    id: "corporate",
    name: "Corporate Formal",
    description: "Traditional enterprise-friendly format",
    wrapperClass: "space-y-6 p-4 text-slate-900",
    headerClass: "border-y-2 border-slate-800 py-4 text-center",
    nameClass: "text-3xl font-serif font-bold text-slate-900",
    titleClass: "text-slate-600",
    contactClass: "justify-center text-slate-700",
    headingClass: "text-slate-800 uppercase tracking-wide",
    skillClass: "bg-slate-200 text-slate-900",
    photoClass: "mx-auto mb-3 h-20 w-20 rounded object-cover",
  },
  {
    id: "finance",
    name: "Finance Analyst",
    description: "Conservative finance and banking resume style",
    wrapperClass: "space-y-5 border border-green-800 p-5 text-slate-900",
    headerClass: "border-b-2 border-green-800 pb-4",
    nameClass: "text-3xl font-serif font-bold text-green-900",
    titleClass: "text-slate-600",
    contactClass: "text-slate-700",
    headingClass: "text-green-900 uppercase tracking-wide",
    skillClass: "bg-green-100 text-green-900",
    photoClass: "h-20 w-20 rounded border-2 border-green-800 object-cover",
  },
  {
    id: "legal",
    name: "Legal Counsel",
    description: "Formal law and compliance CV layout",
    wrapperClass: "space-y-5 p-6 font-serif text-slate-900",
    headerClass: "border-b-4 border-zinc-800 pb-4 text-center",
    nameClass: "text-3xl font-bold text-zinc-900",
    titleClass: "italic text-zinc-600",
    contactClass: "justify-center text-zinc-700",
    headingClass: "text-zinc-900 uppercase tracking-wide",
    skillClass: "bg-zinc-100 text-zinc-900",
    photoClass: "mx-auto mb-3 h-20 w-20 rounded object-cover",
  },
  {
    id: "medical",
    name: "Healthcare CV",
    description: "Calm clinical layout for healthcare professionals",
    wrapperClass: "space-y-6 rounded-xl border border-cyan-200 p-5 text-slate-900",
    headerClass: "flex items-center gap-4 border-b-2 border-cyan-700 pb-4",
    nameClass: "text-3xl font-bold text-cyan-800",
    titleClass: "text-slate-600",
    contactClass: "text-slate-700",
    headingClass: "text-cyan-800",
    skillClass: "bg-cyan-100 text-cyan-900",
    photoClass: "h-20 w-20 rounded-full border-2 border-cyan-700 object-cover",
  },
  {
    id: "designer",
    name: "UX Designer",
    description: "Portfolio-forward design layout",
    wrapperClass: "space-y-6 rounded-2xl border border-pink-200 p-6 text-slate-900",
    headerClass: "flex items-center gap-4 border-b-4 border-pink-500 pb-4",
    nameClass: "text-3xl font-black text-pink-700",
    titleClass: "text-slate-600",
    contactClass: "text-slate-700",
    headingClass: "text-pink-700",
    skillClass: "bg-pink-100 text-pink-900",
    photoClass: "h-20 w-20 rounded-2xl border-2 border-pink-500 object-cover",
    layout: "sidebar",
  },
  {
    id: "creative",
    name: "Creative Studio",
    description: "Bold creative professional template",
    wrapperClass: "space-y-6 rounded-2xl bg-gradient-to-br from-purple-50 to-white p-6 text-slate-900",
    headerClass: "flex items-center gap-4 rounded-xl bg-purple-700 p-5 text-white",
    nameClass: "text-3xl font-bold text-white",
    titleClass: "text-purple-100",
    contactClass: "text-purple-100",
    headingClass: "text-purple-700",
    skillClass: "bg-purple-100 text-purple-900",
    photoClass: "h-20 w-20 rounded-full border-2 border-white object-cover",
    layout: "sidebar",
  },
  {
    id: "sales",
    name: "Sales Growth",
    description: "Revenue-focused layout with energetic orange accents",
    wrapperClass: "space-y-6 rounded-xl border border-orange-200 p-5 text-slate-900",
    headerClass: "flex items-center gap-4 rounded-lg bg-orange-600 p-5 text-white",
    nameClass: "text-3xl font-bold text-white",
    titleClass: "text-orange-100",
    contactClass: "text-orange-100",
    headingClass: "text-orange-700",
    skillClass: "bg-orange-100 text-orange-900",
    photoClass: "h-20 w-20 rounded-full border-2 border-white object-cover",
  },
  {
    id: "marketing",
    name: "Marketing Lead",
    description: "Modern brand and campaign-focused format",
    wrapperClass: "space-y-6 rounded-xl border border-fuchsia-200 p-5 text-slate-900",
    headerClass: "border-b-4 border-fuchsia-600 pb-4",
    nameClass: "text-3xl font-black text-fuchsia-700",
    titleClass: "text-slate-600",
    contactClass: "text-slate-700",
    headingClass: "text-fuchsia-700",
    skillClass: "bg-fuchsia-100 text-fuchsia-900",
    photoClass: "h-20 w-20 rounded-2xl border-2 border-fuchsia-600 object-cover",
  },
  {
    id: "academic",
    name: "Academic CV",
    description: "Publication and education-friendly serif layout",
    wrapperClass: "space-y-5 p-4 font-serif text-slate-900",
    headerClass: "border-b border-slate-500 pb-4 text-left",
    nameClass: "text-3xl font-bold text-slate-900",
    titleClass: "italic text-slate-600",
    contactClass: "text-slate-700",
    headingClass: "text-slate-900",
    skillClass: "bg-slate-100 text-slate-900",
    photoClass: "h-20 w-20 rounded border border-slate-500 object-cover",
  },
  {
    id: "graduate",
    name: "Graduate Starter",
    description: "Early career template emphasizing education and skills",
    wrapperClass: "space-y-5 rounded-xl border border-violet-200 p-5 text-slate-900",
    headerClass: "border-b-2 border-violet-600 pb-4 text-center",
    nameClass: "text-3xl font-bold text-violet-700",
    titleClass: "text-slate-600",
    contactClass: "justify-center text-slate-700",
    headingClass: "text-violet-700",
    skillClass: "bg-violet-100 text-violet-900",
    photoClass: "mx-auto mb-3 h-20 w-20 rounded-full border-2 border-violet-600 object-cover",
  },
  {
    id: "compact",
    name: "Compact Pro",
    description: "Dense format for experienced candidates fitting one page",
    wrapperClass: "space-y-3 p-3 text-slate-900",
    headerClass: "border-b border-slate-400 pb-3",
    nameClass: "text-2xl font-bold text-slate-900",
    titleClass: "text-sm text-slate-600",
    contactClass: "text-xs text-slate-700",
    headingClass: "text-slate-900",
    skillClass: "bg-slate-100 text-slate-800",
    photoClass: "h-16 w-16 rounded-full object-cover",
    layout: "compact",
  },
  {
    id: "premium",
    name: "Premium Card",
    description: "Luxury card-style template for senior roles",
    wrapperClass: "space-y-6 rounded-2xl bg-amber-50 p-6 text-slate-900",
    headerClass: "flex items-center gap-4 rounded-xl border border-amber-300 bg-white p-5",
    nameClass: "text-3xl font-bold text-amber-800",
    titleClass: "text-slate-600",
    contactClass: "text-slate-700",
    headingClass: "text-amber-800",
    skillClass: "bg-amber-200 text-amber-950",
    photoClass: "h-20 w-20 rounded-full border-2 border-amber-400 object-cover",
  },
  {
    id: "clean",
    name: "Clean Recruiter",
    description: "Simple clean format optimized for scanning",
    wrapperClass: "space-y-6 p-5 text-slate-900",
    headerClass: "flex items-center gap-4 border-b border-slate-200 pb-4",
    nameClass: "text-3xl font-semibold text-slate-900",
    titleClass: "text-slate-500",
    contactClass: "text-slate-600",
    headingClass: "text-slate-700",
    skillClass: "bg-slate-50 text-slate-800 ring-1 ring-slate-200",
    photoClass: "h-20 w-20 rounded-full object-cover",
  },
  {
    id: "international",
    name: "International CV",
    description: "Global CV format for remote and international roles",
    wrapperClass: "space-y-6 rounded-xl border border-slate-300 p-6 text-slate-900",
    headerClass: "flex items-center gap-4 border-b-2 border-red-700 pb-4",
    nameClass: "text-3xl font-serif font-bold text-red-800",
    titleClass: "text-slate-600",
    contactClass: "text-slate-700",
    headingClass: "text-red-800",
    skillClass: "bg-red-100 text-red-900",
    photoClass: "h-20 w-20 rounded-full border-2 border-red-700 object-cover",
  },
  {
    id: "platinum",
    name: "Platinum Elite",
    description: "VIP silver-black executive layout for premium roles",
    wrapperClass: "space-y-6 rounded-2xl border border-slate-300 bg-gradient-to-br from-white to-slate-100 p-7 text-slate-900 shadow-sm",
    headerClass: "flex items-center gap-5 rounded-2xl bg-slate-950 p-6 text-white",
    nameClass: "text-4xl font-black tracking-tight text-white",
    titleClass: "text-slate-300",
    contactClass: "text-slate-300",
    headingClass: "text-slate-950 uppercase tracking-wider",
    skillClass: "bg-slate-950 text-slate-100",
    photoClass: "h-24 w-24 rounded-2xl border-2 border-slate-300 object-cover",
    layout: "sidebar",
  },
  {
    id: "neo-luxury",
    name: "Neo Luxury",
    description: "Luxury emerald glass-card style for modern leaders",
    wrapperClass: "space-y-6 rounded-3xl bg-gradient-to-br from-emerald-50 via-white to-teal-50 p-7 text-slate-900",
    headerClass: "flex items-center gap-5 rounded-2xl border border-emerald-200 bg-white/80 p-6 shadow-sm",
    nameClass: "text-4xl font-bold text-emerald-900",
    titleClass: "font-medium text-emerald-700",
    contactClass: "text-slate-700",
    headingClass: "text-emerald-800",
    skillClass: "bg-emerald-700 text-white",
    photoClass: "h-24 w-24 rounded-full border-4 border-emerald-200 object-cover",
  },
  {
    id: "magazine",
    name: "Magazine Pro",
    description: "Editorial magazine-inspired profile layout",
    wrapperClass: "space-y-6 rounded-2xl border border-neutral-200 p-7 text-slate-900",
    headerClass: "border-b-8 border-neutral-950 pb-5 text-center",
    nameClass: "text-5xl font-black uppercase leading-none tracking-tight text-neutral-950",
    titleClass: "mt-2 text-sm uppercase tracking-[0.3em] text-neutral-600",
    contactClass: "justify-center text-neutral-700",
    headingClass: "text-neutral-950 uppercase tracking-widest",
    skillClass: "bg-neutral-950 text-white",
    photoClass: "mx-auto mb-4 h-24 w-24 rounded-full object-cover grayscale",
  },
  {
    id: "founder",
    name: "Founder Mode",
    description: "Bold founder/startup operator template",
    wrapperClass: "space-y-6 rounded-3xl border border-orange-200 bg-orange-50 p-7 text-slate-900",
    headerClass: "flex items-center gap-5 rounded-2xl bg-orange-600 p-6 text-white",
    nameClass: "text-4xl font-black text-white",
    titleClass: "text-orange-100",
    contactClass: "text-orange-100",
    headingClass: "text-orange-800",
    skillClass: "bg-orange-600 text-white",
    photoClass: "h-24 w-24 rounded-2xl border-2 border-white object-cover",
    layout: "sidebar",
  },
  {
    id: "global-exec",
    name: "Global Executive",
    description: "International C-suite template with deep red accents",
    wrapperClass: "space-y-6 border-y-8 border-red-900 p-7 font-serif text-slate-900",
    headerClass: "border-b-2 border-red-900 pb-5 text-center",
    nameClass: "text-4xl font-bold text-red-950",
    titleClass: "italic text-slate-600",
    contactClass: "justify-center text-slate-700",
    headingClass: "text-red-950 uppercase tracking-wide",
    skillClass: "bg-red-100 text-red-950",
    photoClass: "mx-auto mb-4 h-24 w-24 rounded border-2 border-red-900 object-cover",
  },
  {
    id: "investment-banking",
    name: "Investment Banking",
    description: "Elite finance resume with conservative premium styling",
    wrapperClass: "space-y-5 border border-slate-900 p-7 font-serif text-slate-900",
    headerClass: "border-b-4 border-slate-900 pb-4",
    nameClass: "text-4xl font-bold text-slate-950",
    titleClass: "font-medium text-slate-700",
    contactClass: "text-slate-700",
    headingClass: "text-slate-950 uppercase tracking-[0.18em]",
    skillClass: "bg-slate-900 text-white",
    photoClass: "h-20 w-20 rounded border border-slate-900 object-cover",
    layout: "compact",
  },
  {
    id: "ai-researcher",
    name: "AI Researcher",
    description: "Modern research and ML engineer profile layout",
    wrapperClass: "space-y-6 rounded-2xl border border-cyan-200 bg-gradient-to-br from-cyan-50 to-white p-7 font-mono text-slate-900",
    headerClass: "flex items-center gap-5 rounded-2xl bg-slate-950 p-6 text-white",
    nameClass: "text-3xl font-bold text-cyan-300",
    titleClass: "text-slate-300",
    contactClass: "text-slate-300",
    headingClass: "text-cyan-700",
    skillClass: "bg-cyan-100 text-cyan-950 ring-1 ring-cyan-300",
    photoClass: "h-24 w-24 rounded-xl border-2 border-cyan-300 object-cover",
    layout: "sidebar",
  },
  {
    id: "portfolio-showcase",
    name: "Portfolio Showcase",
    description: "Stylish portfolio-first template for creators and builders",
    wrapperClass: "space-y-6 rounded-3xl border border-violet-200 bg-gradient-to-br from-violet-50 via-white to-fuchsia-50 p-7 text-slate-900",
    headerClass: "flex items-center gap-5 rounded-2xl bg-gradient-to-r from-violet-700 to-fuchsia-700 p-6 text-white",
    nameClass: "text-4xl font-black text-white",
    titleClass: "text-violet-100",
    contactClass: "text-violet-100",
    headingClass: "text-violet-800",
    skillClass: "bg-violet-700 text-white",
    photoClass: "h-24 w-24 rounded-3xl border-2 border-white object-cover",
    layout: "sidebar",
  },
  {
    id: "enterprise-director",
    name: "Enterprise Director",
    description: "Large-company director resume with polished hierarchy",
    wrapperClass: "space-y-6 rounded-xl border border-blue-900 p-7 text-slate-900",
    headerClass: "border-b-2 border-blue-900 pb-5",
    nameClass: "text-4xl font-bold tracking-tight text-blue-950",
    titleClass: "font-medium text-blue-800",
    contactClass: "text-slate-700",
    headingClass: "text-blue-950 uppercase tracking-wide",
    skillClass: "bg-blue-950 text-white",
    photoClass: "h-20 w-20 rounded-full border-2 border-blue-900 object-cover",
  },
  {
    id: "strategy-leader",
    name: "Strategy Leader",
    description: "High-impact strategy and operations leadership format",
    wrapperClass: "space-y-6 rounded-2xl bg-stone-100 p-7 text-slate-900",
    headerClass: "flex items-center gap-5 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-stone-300",
    nameClass: "text-4xl font-black text-stone-950",
    titleClass: "text-stone-600",
    contactClass: "text-stone-700",
    headingClass: "text-stone-950",
    skillClass: "bg-stone-800 text-white",
    photoClass: "h-24 w-24 rounded-full border-4 border-stone-200 object-cover",
  },
  {
    id: "corporate-boardroom",
    name: "Corporate Boardroom",
    description: "Fortune 500-style executive template with board-level polish",
    wrapperClass: "space-y-6 border-t-[10px] border-slate-950 bg-white p-8 text-slate-900",
    headerClass: "flex items-center gap-5 border-b-2 border-slate-950 pb-5",
    nameClass: "text-4xl font-serif font-bold tracking-tight text-slate-950",
    titleClass: "font-medium uppercase tracking-[0.18em] text-slate-600",
    contactClass: "text-slate-700",
    headingClass: "text-slate-950 uppercase tracking-[0.2em]",
    skillClass: "bg-slate-950 text-white",
    photoClass: "h-24 w-24 rounded-sm border-2 border-slate-950 object-cover",
  },
  {
    id: "modern-corporate",
    name: "Modern Corporate",
    description: "Clean enterprise resume for managers and senior professionals",
    wrapperClass: "space-y-6 rounded-2xl border border-slate-200 bg-gradient-to-br from-white to-slate-50 p-7 text-slate-900",
    headerClass: "flex items-center gap-5 rounded-xl bg-slate-900 p-6 text-white",
    nameClass: "text-4xl font-bold text-white",
    titleClass: "text-slate-300",
    contactClass: "text-slate-300",
    headingClass: "text-slate-900",
    skillClass: "bg-slate-100 text-slate-950 ring-1 ring-slate-300",
    photoClass: "h-24 w-24 rounded-full border-2 border-white object-cover",
    layout: "sidebar",
  },
  {
    id: "ceo-premium",
    name: "CEO Premium",
    description: "Premium leadership CV with strong executive presence",
    wrapperClass: "space-y-6 rounded-3xl border border-amber-300 bg-amber-50 p-8 text-slate-900",
    headerClass: "flex items-center gap-5 rounded-2xl border border-amber-400 bg-white p-6 shadow-sm",
    nameClass: "text-4xl font-black tracking-tight text-amber-900",
    titleClass: "font-semibold text-amber-700",
    contactClass: "text-slate-700",
    headingClass: "text-amber-900 uppercase tracking-wide",
    skillClass: "bg-amber-700 text-white",
    photoClass: "h-24 w-24 rounded-2xl border-4 border-amber-200 object-cover",
  },
  {
    id: "enterprise-consultant",
    name: "Enterprise Consultant",
    description: "Structured consulting resume for corporate advisory roles",
    wrapperClass: "space-y-5 border-l-[10px] border-indigo-950 bg-white p-7 text-slate-900",
    headerClass: "border-b-4 border-indigo-950 pb-5",
    nameClass: "text-4xl font-bold tracking-tight text-indigo-950",
    titleClass: "font-medium text-indigo-700",
    contactClass: "text-slate-700",
    headingClass: "text-indigo-950 uppercase tracking-[0.16em]",
    skillClass: "bg-indigo-950 text-white",
    photoClass: "h-20 w-20 rounded border-2 border-indigo-950 object-cover",
    layout: "compact",
  },
  {
    id: "vp-operations",
    name: "VP Operations",
    description: "Operational leadership template focused on scale and metrics",
    wrapperClass: "space-y-6 rounded-2xl border border-emerald-900 bg-white p-7 text-slate-900",
    headerClass: "flex items-center gap-5 rounded-xl bg-emerald-950 p-6 text-white",
    nameClass: "text-4xl font-bold text-white",
    titleClass: "text-emerald-100",
    contactClass: "text-emerald-100",
    headingClass: "text-emerald-950 uppercase tracking-wide",
    skillClass: "bg-emerald-100 text-emerald-950 ring-1 ring-emerald-300",
    photoClass: "h-24 w-24 rounded-full border-2 border-emerald-200 object-cover",
  },
];

export function getResumeTemplate(templateId?: string) {
  return (
    ALL_RESUME_TEMPLATES.find((template) => template.id === templateId) ||
    ALL_RESUME_TEMPLATES[0]
  );
}
